apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: packer-cli-vm
  namespace: namespace-1
  labels:
    vm-selector: packer-cli-vm
    vm-lb-06m1: vm-lb-selector
spec:
  className: best-effort-small
  imageName: vmi-06f1807c69d0c34e6
  storageClass: k8s-storage-policy
  powerState: poweredOn
  vmMetadata:
    secretName: packer-cli-vm-bootstrap-secret
    transport: CloudInit
