apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tkg-cluster
  namespace: other-ns
  labels:
    tkg-cluster-selector: tkg-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: tanzukubernetescluster
    version: v1.30.1---vmware.1-fips-tkg.5
    variables:
      - name: vmClass
        value: guaranteed-xsmall
      - name: storageClass
        value: k8s-storage-policy
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: tkg-cluster-nodepool
          replicas: 1
