apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cli-vm-pvc-0
  namespace: namespace-1
  labels:
    vm-selector: cli-vm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: k8s-storage-policy